/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FreeRouteImport } from './routes/free'
import { Route as FreeCookbookRouteImport } from './routes/free-cookbook'
import { Route as PrepRouteImport } from './routes/prep'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAffiliateRouteImport } from './routes/_authenticated/affiliate'
import { Route as AuthenticatedPrepAppRouteImport } from './routes/_authenticated/prep-app'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as RecipesIndexRouteImport } from './routes/recipes.index'
import { Route as RecipesSlugRouteImport } from './routes/recipes.$slug'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as AuthenticatedPrepAppIndexRouteImport } from './routes/_authenticated/prep-app.index'
import { Route as AuthenticatedPrepAppGroceryRouteImport } from './routes/_authenticated/prep-app.grocery'
import { Route as AuthenticatedPrepAppGuidesRouteImport } from './routes/_authenticated/prep-app.guides'
import { Route as AuthenticatedPrepAppKitchenRouteImport } from './routes/_authenticated/prep-app.kitchen'
import { Route as AuthenticatedPrepAppOnboardingRouteImport } from './routes/_authenticated/prep-app.onboarding'
import { Route as AuthenticatedPrepAppPantryRouteImport } from './routes/_authenticated/prep-app.pantry'
import { Route as AuthenticatedPrepAppPlannerRouteImport } from './routes/_authenticated/prep-app.planner'
import { Route as AuthenticatedPrepAppPlansRouteImport } from './routes/_authenticated/prep-app.plans'
import { Route as AuthenticatedPrepAppProfileRouteImport } from './routes/_authenticated/prep-app.profile'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedPrepAppRecipesIndexRouteImport } from './routes/_authenticated/prep-app.recipes.index'
import { Route as AuthenticatedPrepAppRecipesIdRouteImport } from './routes/_authenticated/prep-app.recipes.$id'
import { Route as ApiPublicDownloadCookbookRouteImport } from './routes/api/public/download/cookbook'
import { Route as ApiPublicImgSplatRouteImport } from './routes/api/public/img/$'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicPinterestPublishDueRouteImport } from './routes/api/public/pinterest/publish-due'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as ApiPublicPinterestOauthCallbackRouteImport } from './routes/api/public/pinterest/oauth/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeRoute = FreeRouteImport.update({
  id: '/free',
  path: '/free',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeCookbookRoute = FreeCookbookRouteImport.update({
  id: '/free-cookbook',
  path: '/free-cookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepRoute = PrepRouteImport.update({
  id: '/prep',
  path: '/prep',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAffiliateRoute = AuthenticatedAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrepAppRoute = AuthenticatedPrepAppRouteImport.update({
  id: '/prep-app',
  path: '/prep-app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecipesRoute,
} as any)
const RecipesSlugRoute = RecipesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RecipesRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const AuthenticatedPrepAppIndexRoute =
  AuthenticatedPrepAppIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPrepAppRoute,
  } as any)
const AuthenticatedPrepAppGroceryRoute =
  AuthenticatedPrepAppGroceryRouteImport.update({
    id: '/grocery',
    path: '/grocery',
    getParentRoute: () => AuthenticatedPrepAppRoute,
  } as any)
const AuthenticatedPrepAppGuidesRoute =
  AuthenticatedPrepAppGuidesRouteImport.update({
    id: '/guides',
    path: '/guides',
    getParentRoute: () => AuthenticatedPrepAppRoute,
  } as any)
const AuthenticatedPrepAppKitchenRoute =
  AuthenticatedPrepAppKitchenRouteImport.update({
    id: '/kitchen',
    path: '/kitchen',
    getParentRoute: () => AuthenticatedPrepAppRoute,
  } as any)
const AuthenticatedPrepAppOnboardingRoute =
  AuthenticatedPrepAppOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedPrepAppRoute,
  } as any)
const AuthenticatedPrepAppPantryRoute =
  AuthenticatedPrepAppPantryRouteImport.update({
    id: '/pantry',
    path: '/pantry',
    getParentRoute: () => AuthenticatedPrepAppRoute,
  } as any)
const AuthenticatedPrepAppPlannerRoute =
  AuthenticatedPrepAppPlannerRouteImport.update({
    id: '/planner',
    path: '/planner',
    getParentRoute: () => AuthenticatedPrepAppRoute,
  } as any)
const AuthenticatedPrepAppPlansRoute =
  AuthenticatedPrepAppPlansRouteImport.update({
    id: '/plans',
    path: '/plans',
    getParentRoute: () => AuthenticatedPrepAppRoute,
  } as any)
const AuthenticatedPrepAppProfileRoute =
  AuthenticatedPrepAppProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedPrepAppRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPrepAppRecipesIndexRoute =
  AuthenticatedPrepAppRecipesIndexRouteImport.update({
    id: '/recipes/',
    path: '/recipes/',
    getParentRoute: () => AuthenticatedPrepAppRoute,
  } as any)
const AuthenticatedPrepAppRecipesIdRoute =
  AuthenticatedPrepAppRecipesIdRouteImport.update({
    id: '/recipes/$id',
    path: '/recipes/$id',
    getParentRoute: () => AuthenticatedPrepAppRoute,
  } as any)
const ApiPublicDownloadCookbookRoute =
  ApiPublicDownloadCookbookRouteImport.update({
    id: '/api/public/download/cookbook',
    path: '/api/public/download/cookbook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicImgSplatRoute = ApiPublicImgSplatRouteImport.update({
  id: '/api/public/img/$',
  path: '/api/public/img/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPinterestPublishDueRoute =
  ApiPublicPinterestPublishDueRouteImport.update({
    id: '/api/public/pinterest/publish-due',
    path: '/api/public/pinterest/publish-due',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPinterestOauthCallbackRoute =
  ApiPublicPinterestOauthCallbackRouteImport.update({
    id: '/api/public/pinterest/oauth/callback',
    path: '/api/public/pinterest/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/free': typeof FreeRoute
  '/free-cookbook': typeof FreeCookbookRoute
  '/prep': typeof PrepRoute
  '/privacy': typeof PrivacyRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/affiliate': typeof AuthenticatedAffiliateRoute
  '/prep-app': typeof AuthenticatedPrepAppRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/p/$slug': typeof PSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/prep-app/grocery': typeof AuthenticatedPrepAppGroceryRoute
  '/prep-app/guides': typeof AuthenticatedPrepAppGuidesRoute
  '/prep-app/kitchen': typeof AuthenticatedPrepAppKitchenRoute
  '/prep-app/onboarding': typeof AuthenticatedPrepAppOnboardingRoute
  '/prep-app/pantry': typeof AuthenticatedPrepAppPantryRoute
  '/prep-app/planner': typeof AuthenticatedPrepAppPlannerRoute
  '/prep-app/plans': typeof AuthenticatedPrepAppPlansRoute
  '/prep-app/profile': typeof AuthenticatedPrepAppProfileRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/prep-app/': typeof AuthenticatedPrepAppIndexRoute
  '/prep-app/recipes/$id': typeof AuthenticatedPrepAppRecipesIdRoute
  '/api/public/download/cookbook': typeof ApiPublicDownloadCookbookRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/pinterest/publish-due': typeof ApiPublicPinterestPublishDueRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/prep-app/recipes/': typeof AuthenticatedPrepAppRecipesIndexRoute
  '/api/public/pinterest/oauth/callback': typeof ApiPublicPinterestOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/free': typeof FreeRoute
  '/free-cookbook': typeof FreeCookbookRoute
  '/prep': typeof PrepRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/affiliate': typeof AuthenticatedAffiliateRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/p/$slug': typeof PSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/blog': typeof BlogIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/shop': typeof ShopIndexRoute
  '/prep-app/grocery': typeof AuthenticatedPrepAppGroceryRoute
  '/prep-app/guides': typeof AuthenticatedPrepAppGuidesRoute
  '/prep-app/kitchen': typeof AuthenticatedPrepAppKitchenRoute
  '/prep-app/onboarding': typeof AuthenticatedPrepAppOnboardingRoute
  '/prep-app/pantry': typeof AuthenticatedPrepAppPantryRoute
  '/prep-app/planner': typeof AuthenticatedPrepAppPlannerRoute
  '/prep-app/plans': typeof AuthenticatedPrepAppPlansRoute
  '/prep-app/profile': typeof AuthenticatedPrepAppProfileRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/prep-app': typeof AuthenticatedPrepAppIndexRoute
  '/prep-app/recipes/$id': typeof AuthenticatedPrepAppRecipesIdRoute
  '/api/public/download/cookbook': typeof ApiPublicDownloadCookbookRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/pinterest/publish-due': typeof ApiPublicPinterestPublishDueRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/prep-app/recipes': typeof AuthenticatedPrepAppRecipesIndexRoute
  '/api/public/pinterest/oauth/callback': typeof ApiPublicPinterestOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/free': typeof FreeRoute
  '/free-cookbook': typeof FreeCookbookRoute
  '/prep': typeof PrepRoute
  '/privacy': typeof PrivacyRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/affiliate': typeof AuthenticatedAffiliateRoute
  '/_authenticated/prep-app': typeof AuthenticatedPrepAppRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/p/$slug': typeof PSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/_authenticated/prep-app/grocery': typeof AuthenticatedPrepAppGroceryRoute
  '/_authenticated/prep-app/guides': typeof AuthenticatedPrepAppGuidesRoute
  '/_authenticated/prep-app/kitchen': typeof AuthenticatedPrepAppKitchenRoute
  '/_authenticated/prep-app/onboarding': typeof AuthenticatedPrepAppOnboardingRoute
  '/_authenticated/prep-app/pantry': typeof AuthenticatedPrepAppPantryRoute
  '/_authenticated/prep-app/planner': typeof AuthenticatedPrepAppPlannerRoute
  '/_authenticated/prep-app/plans': typeof AuthenticatedPrepAppPlansRoute
  '/_authenticated/prep-app/profile': typeof AuthenticatedPrepAppProfileRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/prep-app/': typeof AuthenticatedPrepAppIndexRoute
  '/_authenticated/prep-app/recipes/$id': typeof AuthenticatedPrepAppRecipesIdRoute
  '/api/public/download/cookbook': typeof ApiPublicDownloadCookbookRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/pinterest/publish-due': typeof ApiPublicPinterestPublishDueRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/prep-app/recipes/': typeof AuthenticatedPrepAppRecipesIndexRoute
  '/api/public/pinterest/oauth/callback': typeof ApiPublicPinterestOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/checkout'
    | '/contact'
    | '/free'
    | '/free-cookbook'
    | '/prep'
    | '/privacy'
    | '/recipes'
    | '/refund'
    | '/reset-password'
    | '/search'
    | '/shop'
    | '/sitemap.xml'
    | '/terms'
    | '/thank-you'
    | '/admin'
    | '/affiliate'
    | '/prep-app'
    | '/blog/$slug'
    | '/collections/$slug'
    | '/email/unsubscribe'
    | '/p/$slug'
    | '/recipes/$slug'
    | '/shop/$slug'
    | '/blog/'
    | '/recipes/'
    | '/shop/'
    | '/prep-app/grocery'
    | '/prep-app/guides'
    | '/prep-app/kitchen'
    | '/prep-app/onboarding'
    | '/prep-app/pantry'
    | '/prep-app/planner'
    | '/prep-app/plans'
    | '/prep-app/profile'
    | '/lovable/email/suppression'
    | '/prep-app/'
    | '/prep-app/recipes/$id'
    | '/api/public/download/cookbook'
    | '/api/public/img/$'
    | '/api/public/payments/webhook'
    | '/api/public/pinterest/publish-due'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/prep-app/recipes/'
    | '/api/public/pinterest/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/checkout'
    | '/contact'
    | '/free'
    | '/free-cookbook'
    | '/prep'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/thank-you'
    | '/admin'
    | '/affiliate'
    | '/blog/$slug'
    | '/collections/$slug'
    | '/email/unsubscribe'
    | '/p/$slug'
    | '/recipes/$slug'
    | '/shop/$slug'
    | '/blog'
    | '/recipes'
    | '/shop'
    | '/prep-app/grocery'
    | '/prep-app/guides'
    | '/prep-app/kitchen'
    | '/prep-app/onboarding'
    | '/prep-app/pantry'
    | '/prep-app/planner'
    | '/prep-app/plans'
    | '/prep-app/profile'
    | '/lovable/email/suppression'
    | '/prep-app'
    | '/prep-app/recipes/$id'
    | '/api/public/download/cookbook'
    | '/api/public/img/$'
    | '/api/public/payments/webhook'
    | '/api/public/pinterest/publish-due'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/prep-app/recipes'
    | '/api/public/pinterest/oauth/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blog'
    | '/checkout'
    | '/contact'
    | '/free'
    | '/free-cookbook'
    | '/prep'
    | '/privacy'
    | '/recipes'
    | '/refund'
    | '/reset-password'
    | '/search'
    | '/shop'
    | '/sitemap.xml'
    | '/terms'
    | '/thank-you'
    | '/_authenticated/admin'
    | '/_authenticated/affiliate'
    | '/_authenticated/prep-app'
    | '/blog/$slug'
    | '/collections/$slug'
    | '/email/unsubscribe'
    | '/p/$slug'
    | '/recipes/$slug'
    | '/shop/$slug'
    | '/blog/'
    | '/recipes/'
    | '/shop/'
    | '/_authenticated/prep-app/grocery'
    | '/_authenticated/prep-app/guides'
    | '/_authenticated/prep-app/kitchen'
    | '/_authenticated/prep-app/onboarding'
    | '/_authenticated/prep-app/pantry'
    | '/_authenticated/prep-app/planner'
    | '/_authenticated/prep-app/plans'
    | '/_authenticated/prep-app/profile'
    | '/lovable/email/suppression'
    | '/_authenticated/prep-app/'
    | '/_authenticated/prep-app/recipes/$id'
    | '/api/public/download/cookbook'
    | '/api/public/img/$'
    | '/api/public/payments/webhook'
    | '/api/public/pinterest/publish-due'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/prep-app/recipes/'
    | '/api/public/pinterest/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FreeRoute: typeof FreeRoute
  FreeCookbookRoute: typeof FreeCookbookRoute
  PrepRoute: typeof PrepRoute
  PrivacyRoute: typeof PrivacyRoute
  RecipesRoute: typeof RecipesRouteWithChildren
  RefundRoute: typeof RefundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  ShopRoute: typeof ShopRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  PSlugRoute: typeof PSlugRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicDownloadCookbookRoute: typeof ApiPublicDownloadCookbookRoute
  ApiPublicImgSplatRoute: typeof ApiPublicImgSplatRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicPinterestPublishDueRoute: typeof ApiPublicPinterestPublishDueRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
  ApiPublicPinterestOauthCallbackRoute: typeof ApiPublicPinterestOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free': {
      id: '/free'
      path: '/free'
      fullPath: '/free'
      preLoaderRoute: typeof FreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-cookbook': {
      id: '/free-cookbook'
      path: '/free-cookbook'
      fullPath: '/free-cookbook'
      preLoaderRoute: typeof FreeCookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prep': {
      id: '/prep'
      path: '/prep'
      fullPath: '/prep'
      preLoaderRoute: typeof PrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/affiliate': {
      id: '/_authenticated/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AuthenticatedAffiliateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prep-app': {
      id: '/_authenticated/prep-app'
      path: '/prep-app'
      fullPath: '/prep-app'
      preLoaderRoute: typeof AuthenticatedPrepAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof RecipesRoute
    }
    '/recipes/$slug': {
      id: '/recipes/$slug'
      path: '/$slug'
      fullPath: '/recipes/$slug'
      preLoaderRoute: typeof RecipesSlugRouteImport
      parentRoute: typeof RecipesRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_authenticated/prep-app/': {
      id: '/_authenticated/prep-app/'
      path: '/'
      fullPath: '/prep-app/'
      preLoaderRoute: typeof AuthenticatedPrepAppIndexRouteImport
      parentRoute: typeof AuthenticatedPrepAppRoute
    }
    '/_authenticated/prep-app/grocery': {
      id: '/_authenticated/prep-app/grocery'
      path: '/grocery'
      fullPath: '/prep-app/grocery'
      preLoaderRoute: typeof AuthenticatedPrepAppGroceryRouteImport
      parentRoute: typeof AuthenticatedPrepAppRoute
    }
    '/_authenticated/prep-app/guides': {
      id: '/_authenticated/prep-app/guides'
      path: '/guides'
      fullPath: '/prep-app/guides'
      preLoaderRoute: typeof AuthenticatedPrepAppGuidesRouteImport
      parentRoute: typeof AuthenticatedPrepAppRoute
    }
    '/_authenticated/prep-app/kitchen': {
      id: '/_authenticated/prep-app/kitchen'
      path: '/kitchen'
      fullPath: '/prep-app/kitchen'
      preLoaderRoute: typeof AuthenticatedPrepAppKitchenRouteImport
      parentRoute: typeof AuthenticatedPrepAppRoute
    }
    '/_authenticated/prep-app/onboarding': {
      id: '/_authenticated/prep-app/onboarding'
      path: '/onboarding'
      fullPath: '/prep-app/onboarding'
      preLoaderRoute: typeof AuthenticatedPrepAppOnboardingRouteImport
      parentRoute: typeof AuthenticatedPrepAppRoute
    }
    '/_authenticated/prep-app/pantry': {
      id: '/_authenticated/prep-app/pantry'
      path: '/pantry'
      fullPath: '/prep-app/pantry'
      preLoaderRoute: typeof AuthenticatedPrepAppPantryRouteImport
      parentRoute: typeof AuthenticatedPrepAppRoute
    }
    '/_authenticated/prep-app/planner': {
      id: '/_authenticated/prep-app/planner'
      path: '/planner'
      fullPath: '/prep-app/planner'
      preLoaderRoute: typeof AuthenticatedPrepAppPlannerRouteImport
      parentRoute: typeof AuthenticatedPrepAppRoute
    }
    '/_authenticated/prep-app/plans': {
      id: '/_authenticated/prep-app/plans'
      path: '/plans'
      fullPath: '/prep-app/plans'
      preLoaderRoute: typeof AuthenticatedPrepAppPlansRouteImport
      parentRoute: typeof AuthenticatedPrepAppRoute
    }
    '/_authenticated/prep-app/profile': {
      id: '/_authenticated/prep-app/profile'
      path: '/profile'
      fullPath: '/prep-app/profile'
      preLoaderRoute: typeof AuthenticatedPrepAppProfileRouteImport
      parentRoute: typeof AuthenticatedPrepAppRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/prep-app/recipes/': {
      id: '/_authenticated/prep-app/recipes/'
      path: '/recipes'
      fullPath: '/prep-app/recipes/'
      preLoaderRoute: typeof AuthenticatedPrepAppRecipesIndexRouteImport
      parentRoute: typeof AuthenticatedPrepAppRoute
    }
    '/_authenticated/prep-app/recipes/$id': {
      id: '/_authenticated/prep-app/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/prep-app/recipes/$id'
      preLoaderRoute: typeof AuthenticatedPrepAppRecipesIdRouteImport
      parentRoute: typeof AuthenticatedPrepAppRoute
    }
    '/api/public/download/cookbook': {
      id: '/api/public/download/cookbook'
      path: '/api/public/download/cookbook'
      fullPath: '/api/public/download/cookbook'
      preLoaderRoute: typeof ApiPublicDownloadCookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img/$': {
      id: '/api/public/img/$'
      path: '/api/public/img/$'
      fullPath: '/api/public/img/$'
      preLoaderRoute: typeof ApiPublicImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pinterest/publish-due': {
      id: '/api/public/pinterest/publish-due'
      path: '/api/public/pinterest/publish-due'
      fullPath: '/api/public/pinterest/publish-due'
      preLoaderRoute: typeof ApiPublicPinterestPublishDueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pinterest/oauth/callback': {
      id: '/api/public/pinterest/oauth/callback'
      path: '/api/public/pinterest/oauth/callback'
      fullPath: '/api/public/pinterest/oauth/callback'
      preLoaderRoute: typeof ApiPublicPinterestOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPrepAppRouteChildren {
  AuthenticatedPrepAppGroceryRoute: typeof AuthenticatedPrepAppGroceryRoute
  AuthenticatedPrepAppGuidesRoute: typeof AuthenticatedPrepAppGuidesRoute
  AuthenticatedPrepAppKitchenRoute: typeof AuthenticatedPrepAppKitchenRoute
  AuthenticatedPrepAppOnboardingRoute: typeof AuthenticatedPrepAppOnboardingRoute
  AuthenticatedPrepAppPantryRoute: typeof AuthenticatedPrepAppPantryRoute
  AuthenticatedPrepAppPlannerRoute: typeof AuthenticatedPrepAppPlannerRoute
  AuthenticatedPrepAppPlansRoute: typeof AuthenticatedPrepAppPlansRoute
  AuthenticatedPrepAppProfileRoute: typeof AuthenticatedPrepAppProfileRoute
  AuthenticatedPrepAppIndexRoute: typeof AuthenticatedPrepAppIndexRoute
  AuthenticatedPrepAppRecipesIdRoute: typeof AuthenticatedPrepAppRecipesIdRoute
  AuthenticatedPrepAppRecipesIndexRoute: typeof AuthenticatedPrepAppRecipesIndexRoute
}

const AuthenticatedPrepAppRouteChildren: AuthenticatedPrepAppRouteChildren = {
  AuthenticatedPrepAppGroceryRoute: AuthenticatedPrepAppGroceryRoute,
  AuthenticatedPrepAppGuidesRoute: AuthenticatedPrepAppGuidesRoute,
  AuthenticatedPrepAppKitchenRoute: AuthenticatedPrepAppKitchenRoute,
  AuthenticatedPrepAppOnboardingRoute: AuthenticatedPrepAppOnboardingRoute,
  AuthenticatedPrepAppPantryRoute: AuthenticatedPrepAppPantryRoute,
  AuthenticatedPrepAppPlannerRoute: AuthenticatedPrepAppPlannerRoute,
  AuthenticatedPrepAppPlansRoute: AuthenticatedPrepAppPlansRoute,
  AuthenticatedPrepAppProfileRoute: AuthenticatedPrepAppProfileRoute,
  AuthenticatedPrepAppIndexRoute: AuthenticatedPrepAppIndexRoute,
  AuthenticatedPrepAppRecipesIdRoute: AuthenticatedPrepAppRecipesIdRoute,
  AuthenticatedPrepAppRecipesIndexRoute: AuthenticatedPrepAppRecipesIndexRoute,
}

const AuthenticatedPrepAppRouteWithChildren =
  AuthenticatedPrepAppRoute._addFileChildren(AuthenticatedPrepAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAffiliateRoute: typeof AuthenticatedAffiliateRoute
  AuthenticatedPrepAppRoute: typeof AuthenticatedPrepAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAffiliateRoute: AuthenticatedAffiliateRoute,
  AuthenticatedPrepAppRoute: AuthenticatedPrepAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface RecipesRouteChildren {
  RecipesSlugRoute: typeof RecipesSlugRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
}

const RecipesRouteChildren: RecipesRouteChildren = {
  RecipesSlugRoute: RecipesSlugRoute,
  RecipesIndexRoute: RecipesIndexRoute,
}

const RecipesRouteWithChildren =
  RecipesRoute._addFileChildren(RecipesRouteChildren)

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FreeRoute: FreeRoute,
  FreeCookbookRoute: FreeCookbookRoute,
  PrepRoute: PrepRoute,
  PrivacyRoute: PrivacyRoute,
  RecipesRoute: RecipesRouteWithChildren,
  RefundRoute: RefundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  ShopRoute: ShopRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  PSlugRoute: PSlugRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicDownloadCookbookRoute: ApiPublicDownloadCookbookRoute,
  ApiPublicImgSplatRoute: ApiPublicImgSplatRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicPinterestPublishDueRoute: ApiPublicPinterestPublishDueRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
  ApiPublicPinterestOauthCallbackRoute: ApiPublicPinterestOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
